---
create_containers: 2
default_container_name: docker
default_container_image: ubuntu
default_container_command: sleep 1d
docker_portainer_version: "latest"
docker_portainer_container_name: "portainer"
docker_portainer_container_volume_base: "/opt/docker"
docker_portainer_port: "9000"
docker_portainer_initial_database_file: ""
docker_portainer_pull: "no"
docker_portainer_state: "started"
docker_portainer_restart_policy: "always"
