---
- name: Installing rke2 worker
  hosts: rke2workers
  become: true
  remote_user: ubuntu
  tasks:

  - name: Download RKE2
    shell: curl -sfL https://get.rke2.io | sudo INSTALL_RKE2_VERSION=v1.18.12-beta1+rke2r2 INSTALL_RKE2_TYPE="agent" sh -

  - name: apt-get update
    shell: sudo apt-get update

  - name: apt upgrade
    shell: sudo apt-get -y upgrade

  - name: install iscsid
    shell: apt-get install open-iscsi
  - name: enable iscsid
    shell: systemctl enable iscsid
  - name: start iscsid
    shell: systemctl start iscsid         

  - name: Install Python3
    shell: sudo apt-get install -y python3-venv python3-wheel python3-pip

  - name: Git clone
    shell: git clone https://github.com/rancher/rke2.git

  - name: pip3 install
    shell: pip3 install -r rke2/contrib/custom-image-kubelet/requirements.txt

  - name: genconfig
    shell: sudo /usr/bin/python3 /home/ubuntu/rke2/contrib/custom-image-kubelet/genconfig.py --release-url https://distro.eks.amazonaws.com/kubernetes-1-18/kubernetes-1-18-eks-1.yaml

  - name: enable rke2-server
    shell: sudo systemctl enable rke2-agent

  - name: mkdir
    shell: sudo mkdir -p /etc/rancher/rke2/

  - name: Copy the file from master to rke2-worker0
    copy:
     src: buffer/rke2manager/etc/rancher/rke2/config2.yaml
     dest: /etc/rancher/rke2/

  - name: rename config.yaml
    shell: sudo mv /etc/rancher/rke2/config2.yaml /etc/rancher/rke2/config.yaml

  - name: start rke2 agent
    shell: sudo systemctl start rke2-agent.service
