---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml
# Install and configure Docker
  tasks:
    - name: "Build hosts file"
      lineinfile: dest=/etc/hosts
        state=present
        dest=/etc/hosts
        regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_ssh_host }} {{item}}"
      with_items: "{{ groups['all'] }}"
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Pull default Docker image
      docker_image:
        name: "{{ default_container_image }}"
        source: pull


# Create Docker Swarm
- name: initialize docker swarm
  hosts: swarm-managers
  roles:
    - docker-swarm-init
- name: add workers to the swarm
  hosts: swarm-workers
  roles:
    - docker-swarm-add-worker
# Deploy portainer image
- name: install portainer
  hosts: swarm-manager
  vars_files:
    - vars/default.yml
  roles:
    - portainer
